spring:
  application:
    name: sk_pjt2_back_chat

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://localhost/sk_pjt2_chat
      port: 27017

  datasource:
    url: jdbc:mysql://localhost:3306/sk_pjt2_chat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: p1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070

